language: php
dist: trusty
sudo: false
php: 7.3

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  
env:
  - COMPOSER_MEMORY_LIMIT=-1

branches:
  only:
    - /[0-9]+\.x/

mysql:
  database: thunder
  username: root
  encoding: utf8

before_install:
  - source ./scripts/travis/01-setup-environment.sh

script:
# Installing thunder is the actual test
  - bash -x -e ./scripts/travis/02-install-thunder.sh
